# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eebe85061ec9684bcfe6aa5fa202a2591064fae3ac89559e17a20a333a5c8a5d4b80f0b6e85f77be0d3b8a8573593917b2cff8dfd8983034b37e34285e9c3dd9

test:
  secret_key_base: b00169a190208aea1fe428402626ce6cb31b822b3e2c5a20faa67ee400991f8468dde96e250d86449f56eb9ff4f6ae09e29fccde5ca8b6c6ba783162ee101295

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
