# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f989673959f2bb0d0847de1e92b5ad6ca05624bc0b45014113b96b2c37dbf0fea232c3bd0e9cb360fcac80215be34c7c5444e0a3ff2e1044afaf10b62d2fb024

test:
  secret_key_base: 2bc63d21b9911dac54b0de1de7cb0ce9ac65af0c2df3d580259a346bb2a5ae409e12d6e0e5ec2ce28d986287798301cc2b0a7436f24ef9c2f7028a6df84a53f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
