# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b4480919d626bb30b29f2e754e86e66705777c52143890324d51bcfab7f7c0fc5fcee6d8a143592cd5eb8032fbc8d5c695c327e1611c9742874c21ad4fadf32

test:
  secret_key_base: 75aec285b8171b7f618248547144eb8f789e7694b1002b503094d3c96ff77bf2a81dd8827dc23ec62a33d9430c052ce8919ff45d8d6fbefe3a4bcc3675839175

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
